# Generated by Django 6.0.3 on 2026-03-17 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('job', models.IntegerField(choices=[(1, 'Site Reliability Engineer'), (2, 'Developer'), (3, 'Manager'), (4, 'Director')])),
                ('activate', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date(2026, 3, 17))),
            ],
        ),
    ]
