# Generated by Django 6.0.3 on 2026-03-17 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='updated_at',
            field=models.DateField(default=datetime.date(2026, 3, 17)),
        ),
    ]
