# Generated by Django 6.0.3 on 2026-03-17 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
