steps:
  - id: build-application
    name: docker
    args:
      - docker
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:${COMMIT_SHA}
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:latest
      - .

  - id: push-application
    name: docker
    args:
      - docker
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:${COMMIT_SHA}

  - id: perform-migration
    name: us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:${COMMIT_SHA}
    entrypoint: python3
    args:
      - manage.py
      - migrate
    env:
      - PG_USER_NAME=${_PG_USER_NAME}
      - PG_USER_HOST=${_PG_USER_HOST}
      - PG_USER_PORT=${_PG_USER_PORT}
      - PG_USER_USER=${_PG_USER_USER}
      - PG_USER_PASSWORD=${_PG_USER_PASSWORD}

  - id: deploy-image
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_ENVIRONMENT}-app-django-run-service
      - --image
      - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:${COMMIT_SHA}
      - --region
      - us-central1
      - --allow-unauthenticated

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:${COMMIT_SHA}
  - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:latest

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/${_PROJECT_ID_NUMBER}/secrets/PG_USER_NAME/versions/1
      env: _PG_USER_NAME
    - versionName: projects/${_PROJECT_ID_NUMBER}/secrets/PG_USER_HOST/versions/1
      env: _PG_USER_HOST
    - versionName: projects/${_PROJECT_ID_NUMBER}/secrets/PG_USER_PORT/versions/1
      env: _PG_USER_PORT
    - versionName: projects/${_PROJECT_ID_NUMBER}/secrets/PG_USER_USER/versions/1
      env: _PG_USER_USER
    - versionName: projects/${_PROJECT_ID_NUMBER}/secrets/PG_USER_PASSWORD/versions/1
      env: _PG_USER_PASSWORD