steps:
  - id: build-application
    name: docker
    args:
      - docker
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:${COMMIT_SHA}
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:latest
      - .

  - id: push-application
    name: docker
    args:
      - docker
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:${COMMIT_SHA}

  - id: deploy-image
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_ENVIRONMENT}-app-django-run-service
      - --image
      - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:${COMMIT_SHA}
      - --region
      - us-central1
      - --allow-unauthenticated

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:${COMMIT_SHA}
  - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:latest

options:
  logging: CLOUD_LOGGING_ONLY