steps:
  - id: build-application
    name: docker
    args:
      - docker
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:${COMMIT_SHA}
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:latest
      - .
    waitFor:
      - '-'

  - id: deploy-image
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - djangoapp
      - --image
      - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:${COMMIT_SHA}
      - --region
      - us-central1
      - --allow-unathenticated
  
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:${COMMIT_SHA}
  - us-central1-docker.pkg.dev/$PROJECT_ID/django-app/django-app:latest

options:
  logging: CLOUD_LOGGING_ONLY